# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DangNhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import bgr_qrc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DangNhapWindow(object):
    def setupUi(self, DangNhapWindow):
        DangNhapWindow.setObjectName("DangNhapWindow")
        DangNhapWindow.resize(600, 400)
        DangNhapWindow.setStyleSheet("\n"
                                     "QMainWindow{\n"
                                     " border-image: url(:/background/image/Nen-xanh-duong-pastel.ng.jpg);\n"
                                     "background-color: rgb(0, 255, 255);\n"
                                     "}\n"
                                     "")
        self.centralwidget = QtWidgets.QWidget(DangNhapWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 311, 421))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "hop-dong-dien-tu-va-chu-ky-so-1.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 40, 41, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("HYde (1).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 43, 91, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 100, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(490, 100, 75, 31))
        self.pushButton_register.setObjectName("pushButton_register")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 220, 47, 13))
        self.label_5.setObjectName("label_5")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(430, 260, 75, 31))
        self.pushButton_login.setObjectName("pushButton_login")
        self.Text_email = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_email.setGeometry(QtCore.QRect(390, 150, 191, 31))
        self.Text_email.setObjectName("Text_email")
        self.Text_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_pass.setGeometry(QtCore.QRect(390, 210, 191, 31))
        self.Text_pass.setObjectName("Text_pass")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 320, 211, 81))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        DangNhapWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DangNhapWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        DangNhapWindow.setMenuBar(self.menubar)

        self.retranslateUi(DangNhapWindow)
        QtCore.QMetaObject.connectSlotsByName(DangNhapWindow)

    def retranslateUi(self, DangNhapWindow):
        _translate = QtCore.QCoreApplication.translate
        DangNhapWindow.setWindowTitle(
            _translate("DangNhapWindow", "MainWindow"))
        self.label_3.setText(_translate("DangNhapWindow", "MOON.eContract"))
        self.pushButton.setText(_translate("DangNhapWindow", "ĐĂNG NHẬP"))
        self.pushButton_register.setText(
            _translate("DangNhapWindow", "ĐĂNG KÝ"))
        self.label_4.setText(_translate("DangNhapWindow", "Email"))
        self.label_5.setText(_translate("DangNhapWindow", "Mật Khẩu"))
        self.pushButton_login.setText(
            _translate("DangNhapWindow", "ĐĂNG NHẬP"))
        self.label_6.setText(_translate(
            "DangNhapWindow", "   © Bản quyền thuộc về Moon-eContract"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DangNhapWindow = QtWidgets.QMainWindow()
    ui = Ui_DangNhapWindow()
    ui.setupUi(DangNhapWindow)
    DangNhapWindow.show()
    sys.exit(app.exec_())
