# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DangKy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bgr_qrc

class Ui_DangKyWindow(object):
    def setupUi(self, DangKyWindow):
        DangKyWindow.setObjectName("DangKyWindow")
        DangKyWindow.resize(600, 400)
        DangKyWindow.setStyleSheet("\n"
                                     "QMainWindow{\n"
                                     " border-image: url(:/background/image/Nen-xanh-duong-pastel.ng.jpg);\n"
                                     "background-color: rgb(0, 255, 255);\n"
                                     "}\n"
                                     "")
        self.centralwidget = QtWidgets.QWidget(DangKyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 43, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 73, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 73, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 153, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 150, 81, 20))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(290, 100, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(290, 180, 181, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(30, 180, 181, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 233, 61, 20))
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(30, 260, 181, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(290, 257, 181, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 230, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 7, 41, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/HAMATASURIMA/Desktop/HYde (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 10, 91, 31))
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 320, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(520, 360, 75, 31))
        self.pushButton_Back.setObjectName("pushButton_Back")
        DangKyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DangKyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        DangKyWindow.setMenuBar(self.menubar)

        self.retranslateUi(DangKyWindow)
        QtCore.QMetaObject.connectSlotsByName(DangKyWindow)

    def retranslateUi(self, DangKyWindow):
        _translate = QtCore.QCoreApplication.translate
        DangKyWindow.setWindowTitle(_translate("DangKyWindow", "MainWindow"))
        self.label.setText(_translate("DangKyWindow", "THÔNG TIN ĐĂNG KÝ"))
        self.label_2.setText(_translate("DangKyWindow", "TÊN DOANH NGHIỆP"))
        self.label_3.setText(_translate("DangKyWindow", "MÃ SỐ THUẾ"))
        self.label_4.setText(_translate("DangKyWindow", "HỌ VÀ TÊN"))
        self.label_7.setText(_translate("DangKyWindow", "SỐ ĐIỆN THOẠI"))
        self.label_5.setText(_translate("DangKyWindow", "EMAIL"))
        self.label_6.setText(_translate("DangKyWindow", "Email"))
        self.label_9.setText(_translate("DangKyWindow", "MOON.eContract"))
        self.pushButton_2.setText(_translate("DangKyWindow", "ĐĂNG KÝ"))
        self.pushButton_Back.setText(_translate("DangKyWindow", "TRỞ VỀ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DangKyWindow = QtWidgets.QMainWindow()
    ui = Ui_DangKyWindow()
    ui.setupUi(DangKyWindow)
    DangKyWindow.show()
    sys.exit(app.exec_())
