# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiHopDong.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bgr_qrc

class Ui_HopDongWindow(object):
    def setupUi(self, HopDongWindow):
        HopDongWindow.setObjectName("HopDongWindow")
        HopDongWindow.resize(600, 300)
        HopDongWindow.setStyleSheet("\n"
                                    "QMainWindow{\n"
                                    " border-image: url(:/background/image/Nen-xanh-duong-pastel.ng.jpg);\n"
                                    "background-color: rgb(0, 255, 255);\n"
                                    "}\n"
                                    "")
        self.centralwidget = QtWidgets.QWidget(HopDongWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 51, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_gui = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gui.setGeometry(QtCore.QRect(230, 230, 75, 31))
        self.pushButton_gui.setObjectName("pushButton_gui")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(510, 240, 75, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 47, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(
            "C:/Users/HAMATASURIMA/Desktop/HYde (1).png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 190, 41, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file.setGeometry(QtCore.QRect(490, 180, 75, 31))
        self.pushButton_file.setObjectName("pushButton_file")
        self.Text = QtWidgets.QLineEdit(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(140, 60, 311, 31))
        self.Text.setObjectName("Text")
        self.Text_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_2.setGeometry(QtCore.QRect(140, 120, 311, 31))
        self.Text_2.setObjectName("Text_2")
        self.Text_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_3.setGeometry(QtCore.QRect(140, 180, 311, 31))
        self.Text_3.setObjectName("Text_3")
        HopDongWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HopDongWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        HopDongWindow.setMenuBar(self.menubar)

        self.retranslateUi(HopDongWindow)
        QtCore.QMetaObject.connectSlotsByName(HopDongWindow)

    def retranslateUi(self, HopDongWindow):
        _translate = QtCore.QCoreApplication.translate
        HopDongWindow.setWindowTitle(_translate("HopDongWindow", "MainWindow"))
        self.label.setText(_translate("HopDongWindow", "HỢP ĐỒNG ĐIỆN TỬ"))
        self.label_2.setText(_translate("HopDongWindow", "Gửi đến"))
        self.pushButton_gui.setText(_translate("HopDongWindow", "GỬI"))
        self.pushButton_back.setText(_translate("HopDongWindow", "TRỞ VỀ"))
        self.label_3.setText(_translate("HopDongWindow", "Tiêu đề"))
        self.label_4.setText(_translate("HopDongWindow", "File gửi"))
        self.pushButton_file.setText(_translate("HopDongWindow", "Chọn file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HopDongWindow = QtWidgets.QMainWindow()
    ui = Ui_HopDongWindow()
    ui.setupUi(HopDongWindow)
    HopDongWindow.show()
    sys.exit(app.exec_())
