# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 290)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "    border-image:url(:/pic/bgr.jpg);\n"
                                 "    background-color: rgb(0, 255, 255);\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(490, 230, 101, 31))
        self.Back.setStyleSheet(
            "font: 75 14pt \"MS Shell Dlg 2\";color:rgb(0, 0, 0)")
        self.Back.setObjectName("Back")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 50, 111, 31))
        self.pushButton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.Result = QtWidgets.QLabel(self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(70, 170, 61, 31))
        self.Result.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.Result.setObjectName("Result")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 31))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.Numbtn1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Numbtn1.setGeometry(QtCore.QRect(140, 50, 111, 31))
        self.Numbtn1.setObjectName("Numbtn1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 120, 111, 31))
        self.pushButton_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 41, 21))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.Numbtn2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Numbtn2.setGeometry(QtCore.QRect(280, 50, 111, 31))
        self.Numbtn2.setObjectName("Numbtn2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 91, 31))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.Text = QtWidgets.QLineEdit(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(140, 120, 251, 31))
        self.Text.setObjectName("Text")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 230, 91, 31))
        self.pushButton_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 240, 211, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.pushButton.clicked.connect(self.encrypt)
        self.pushButton_2.clicked.connect(self.decrypt)
        self.pushButton_3.clicked.connect(self.copyToClipboard)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Back.setText(_translate("MainWindow", "BACK"))
        self.pushButton.setText(_translate("MainWindow", "Encrypt"))
        self.Result.setText(_translate("MainWindow", "Result:"))
        self.label.setText(_translate("MainWindow", "Enter number:"))
        self.pushButton_2.setText(_translate("MainWindow", "Decrypt"))
        self.label_2.setText(_translate("MainWindow", "RSA"))
        self.label_3.setText(_translate(
            "MainWindow", "Enter two prime numbers"))
        self.label_4.setText(_translate("MainWindow", "Enter text:"))
        self.pushButton_3.setText(_translate("MainWindow", "COPY"))

    def encrypt(self):

        p = 0
        q = 0
        chiper = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!, "
        public_key = 0
        secret_key = 0
        plain_text = ""
        encrypted_text = ""
        p = self.Numbtn1.text()

        q = self.Numbtn2.text()
        p = int(p)
        q = int(q)
        n = p * q
        z = (p-1) * (q-1)

        for i in range(1, 10000):
            if 0 != z % i:
                public_key = round(i)
                break

        for j in range(0, 10000):
            d = 1 + (j * z)
            d2 = d / public_key
            if 0 == d % public_key:
                secret_key = round(d2)
                break
        plain_text = self.Text.text()
        encrypted_text = ""
        for k in plain_text:
            m = 0
            for l in chiper:
                if k == l:
                    if m < 10:
                        m = m + 00
                    encrypted_text = encrypted_text + \
                        (str((m ** public_key) % n)) + " "
                    break
                m += 1

        self.Result.setText(str(encrypted_text))

    def decrypt(self):

        p = 0
        q = 0
        chiper = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!, "
        public_key = 0
        secret_key = 0
        plain_text = ""
        encrypted_text = ""
        p = self.Numbtn1.text()
        q = self.Numbtn2.text()
        p = int(p)
        q = int(q)
        n = p * q
        z = (p-1) * (q-1)

        for i in range(1, 10000):
            if 0 != z % i:
                public_key = round(i)
                break

        for j in range(0, 10000):
            d = 1 + (j * z)
            d2 = d / public_key
            if 0 == d % public_key:
                secret_key = round(d2)
                break

        encrypted_text = self.Text.text()
        plain_text = ""
        for s in encrypted_text.split(" "):
            for k in chiper:
                m = 0
                for l in chiper:
                    if k == l:
                        if s == (str((m ** public_key) % n)):
                            plain_text = plain_text + l
                        break
                    m += 1

        self.Result.setText(str(plain_text))

    def copyToClipboard(self):
        cb = QApplication.clipboard()
        cb.clear(mode=cb.Clipboard)
        cb.setText(self.Result.text(), mode=cb.Clipboard)
        self.label_5.setText('Content is copied')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
