# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiHopDong.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication
from xulykey import RSA
import docx2txt
from client import main_client


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 51, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_gui = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gui.setGeometry(QtCore.QRect(230, 230, 75, 31))
        self.pushButton_gui.setObjectName("pushButton_gui")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(510, 240, 75, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 47, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(
            "C:/Users/HAMATASURIMA/Desktop/HYde (1).png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 190, 41, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file.setGeometry(QtCore.QRect(490, 180, 75, 31))
        self.pushButton_file.setObjectName("pushButton_file")
        self.Text = QtWidgets.QLineEdit(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(140, 60, 311, 31))
        self.Text.setObjectName("Text")
        self.Text_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_2.setGeometry(QtCore.QRect(140, 120, 311, 31))
        self.Text_2.setObjectName("Text_2")
        self.Text_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Text_3.setGeometry(QtCore.QRect(140, 180, 311, 31))
        self.Text_3.setObjectName("Text_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.pushButton_file.clicked.connect(self.linkto)
        self.pushButton_gui.clicked.connect(self.result)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HỢP ĐỒNG ĐIỆN TỬ"))
        self.label_2.setText(_translate("MainWindow", "Gửi đến"))
        self.pushButton_gui.setText(_translate("MainWindow", "GỬI"))
        self.pushButton_back.setText(_translate("MainWindow", "TRỞ VỀ"))
        self.label_3.setText(_translate("MainWindow", "Tiêu đề"))
        self.label_4.setText(_translate("MainWindow", "File gửi"))
        self.pushButton_file.setText(_translate("MainWindow", "Chọn file"))

    def result(self):
        self.rsa = RSA(keysize=32)

        msg = docx2txt.process(self.Text_3.text())
        email = self.Text.text()
        tieude = self.Text_2.text()

        enc = self.rsa.encrypt(msg)

        f = open("tieude.txt", "w")
        f.write(tieude)
        f.close()

        f = open("email.txt", "w")
        f.write(email)
        f.close()

        f = open("secretkey.txt", "w")
        f.write(str(self.rsa.d))
        f.close()

        f = open("data/data.txt", "w")
        f.write(enc)
        f.close()
        print("ok")
        main_client()
        print("ok")

    def linkto(self):
        link = QFileDialog.getOpenFileName(filter='*.doc *.docx')
        self.Text_3.setText(link[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
