# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TraHopDong.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TraHopDongWin(object):
    def setupUi(self, TraHopDongWin):
        TraHopDongWin.setObjectName("TraHopDongWin")
        TraHopDongWin.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(TraHopDongWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 47, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("image/HYde (1).png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_ManHinh = QtWidgets.QLabel(self.centralwidget)
        self.label_ManHinh.setGeometry(QtCore.QRect(20, 40, 641, 571))
        self.label_ManHinh.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ManHinh.setText("")
        self.label_ManHinh.setPixmap(QtGui.QPixmap("image_nguoi_nhan/1.png"))
        self.label_ManHinh.setScaledContents(True)
        self.label_ManHinh.setObjectName("label_ManHinh")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 620, 311, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(350, 620, 311, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_trove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trove.setGeometry(QtCore.QRect(790, 640, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_trove.setFont(font)
        self.pushButton_trove.setObjectName("pushButton_trove")
        self.pushButton_ImageHopDong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ImageHopDong.setGeometry(QtCore.QRect(720, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ImageHopDong.setFont(font)
        self.pushButton_ImageHopDong.setObjectName("pushButton_ImageHopDong")
        self.label_ManHinh_ChuKy = QtWidgets.QLabel(self.centralwidget)
        self.label_ManHinh_ChuKy.setGeometry(QtCore.QRect(680, 110, 201, 201))
        self.label_ManHinh_ChuKy.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ManHinh_ChuKy.setText("")
        self.label_ManHinh_ChuKy.setPixmap(QtGui.QPixmap("image/tải xuống.png"))
        self.label_ManHinh_ChuKy.setScaledContents(True)
        self.label_ManHinh_ChuKy.setObjectName("label_ManHinh_ChuKy")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 90, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_ManHinh_ChuKy_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ManHinh_ChuKy_2.setGeometry(QtCore.QRect(680, 360, 201, 201))
        self.label_ManHinh_ChuKy_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ManHinh_ChuKy_2.setText("")
        self.label_ManHinh_ChuKy_2.setPixmap(QtGui.QPixmap("image_nguoi_gui/chuky.png"))
        self.label_ManHinh_ChuKy_2.setScaledContents(True)
        self.label_ManHinh_ChuKy_2.setObjectName("label_ManHinh_ChuKy_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 330, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        TraHopDongWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TraHopDongWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        TraHopDongWin.setMenuBar(self.menubar)

        self.retranslateUi(TraHopDongWin)
        QtCore.QMetaObject.connectSlotsByName(TraHopDongWin)

    def retranslateUi(self, TraHopDongWin):
        _translate = QtCore.QCoreApplication.translate
        TraHopDongWin.setWindowTitle(_translate("TraHopDongWin", "MainWindow"))
        self.label.setText(_translate("TraHopDongWin", "HỢP ĐỒNG ĐIỆN TỬ"))
        self.pushButton_back.setText(_translate("TraHopDongWin", "<"))
        self.pushButton_next.setText(_translate("TraHopDongWin", ">"))
        self.pushButton_trove.setText(_translate("TraHopDongWin", "TRỞ VỀ"))
        self.pushButton_ImageHopDong.setText(_translate("TraHopDongWin", "HỢP ĐỒNG"))
        self.label_2.setText(_translate("TraHopDongWin", "CHỬ KÝ ĐỐI TÁC"))
        self.label_3.setText(_translate("TraHopDongWin", "CHỬ KÝ ADMIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TraHopDongWin = QtWidgets.QMainWindow()
    ui = Ui_TraHopDongWin()
    ui.setupUi(TraHopDongWin)
    TraHopDongWin.show()
    sys.exit(app.exec_())
