# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrangChu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import bgr_qrc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrangChuWindow(object):
    def setupUi(self, TrangChuWindow):
        TrangChuWindow.setObjectName("TrangChuWindow")
        TrangChuWindow.resize(600, 400)
        TrangChuWindow.setStyleSheet("QMainWindow{\n"
                                     " border-image: url(:/background/image/Nen-xanh-duong-pastel.ng.jpg);\n"
                                     "background-color: rgb(0, 255, 255);\n"
                                     "}\n"
                                     "\n"
                                     "")
        self.centralwidget = QtWidgets.QWidget(TrangChuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 330, 601, 81))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 491, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image/header2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 601, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 47, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("image/HYde (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 292, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 292, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 292, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 292, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_GuiHopDong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GuiHopDong.setGeometry(QtCore.QRect(40, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_GuiHopDong.setFont(font)
        self.pushButton_GuiHopDong.setObjectName("pushButton_GuiHopDong")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(490, 2, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 0, 41, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(
            "image/png-clipart-computer-icons-computer-servers-administrator-miscellaneous-logo-thumbnail.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 330, 601, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_GiaiMa = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GiaiMa.setGeometry(QtCore.QRect(330, 210, 75, 31))
        self.pushButton_GiaiMa.setObjectName("pushButton_GiaiMa")
        self.dangXuatButton = QtWidgets.QPushButton(self.centralwidget)
        self.dangXuatButton.setGeometry(QtCore.QRect(414, 2, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dangXuatButton.setFont(font)
        self.dangXuatButton.setObjectName("dangXuatButton")
        self.pushButton_NhanHopDong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NhanHopDong.setGeometry(QtCore.QRect(180, 210, 75, 31))
        self.pushButton_NhanHopDong.setObjectName("pushButton_NhanHopDong")
        self.pushButton_ShowHopDong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ShowHopDong.setGeometry(QtCore.QRect(460, 210, 75, 31))
        self.pushButton_ShowHopDong.setObjectName("pushButton_ShowHopDong")
        TrangChuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrangChuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        TrangChuWindow.setMenuBar(self.menubar)

        self.retranslateUi(TrangChuWindow)
        QtCore.QMetaObject.connectSlotsByName(TrangChuWindow)

    def retranslateUi(self, TrangChuWindow):
        _translate = QtCore.QCoreApplication.translate
        TrangChuWindow.setWindowTitle(
            _translate("TrangChuWindow", "MainWindow"))
        self.label.setText(_translate(
            "TrangChuWindow", "                                                                    © Bản quyền thuộc về Moon-eContract"))
        self.label_3.setText(_translate(
            "TrangChuWindow", "_________________________________________________________________________________________________________"))
        self.label_5.setText(_translate("TrangChuWindow", "MOON.eContract"))
        self.label_6.setText(_translate("TrangChuWindow", "Hi Admin!"))
        self.pushButton.setText(_translate("TrangChuWindow", "Sản Phẩm"))
        self.pushButton_2.setText(_translate("TrangChuWindow", "Dịch vụ"))
        self.pushButton_3.setText(_translate("TrangChuWindow", "Chính sách"))
        self.pushButton_4.setText(_translate("TrangChuWindow", "Liên hệ"))
        self.label_7.setText(_translate("TrangChuWindow", "Khác"))
        self.label_8.setText(_translate("TrangChuWindow", "Tổng quan"))
        self.pushButton_GuiHopDong.setText(
            _translate("TrangChuWindow", "Tạo Hợp Đồng"))
        self.pushButton_6.setText(_translate("TrangChuWindow", "ADMIN"))
        self.label_10.setText(_translate(
            "TrangChuWindow", "_________________________________________________________________________________________________________"))
        self.pushButton_GiaiMa.setText(_translate("TrangChuWindow", "Giải Mã"))
        self.dangXuatButton.setText(_translate("TrangChuWindow", "Đăng xuất"))
        self.pushButton_NhanHopDong.setText(
            _translate("TrangChuWindow", "Nhận"))
        self.pushButton_ShowHopDong.setText(
            _translate("TrangChuWindow", "Hợp Đồng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrangChuWindow = QtWidgets.QMainWindow()
    ui = Ui_TrangChuWindow()
    ui.setupUi(TrangChuWindow)
    TrangChuWindow.show()
    sys.exit(app.exec_())
